Models/Wedding.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace WeddingProj.Models
{
    public class Wedding
    {
        [Key]
        public int WeddingId { get; set; }

        [Required(ErrorMessage = "Is required!")]
        [MinLength(3, ErrorMessage = "Must be greater than 3!")]
        [Display(Name = "Wedder1 Name")]
        public string Wedder1Name { get; set; }

        [Required(ErrorMessage = "Is required!")]
        [MinLength(3, ErrorMessage = "Must be greater than 3!")]
        [Display(Name = "Wedder2 Name")]
        public string Wedder2Name { get; set; }

        [Required(ErrorMessage = "Is required!")]
        [MinLength(3, ErrorMessage = "Must be greater than 3!")]
        [Display(Name = "Wedding Address")]
        public string WeddingAddress { get; set; }

        [Required(ErrorMessage = "Is required!")]
        [DataType(DataType.Date)]
        [Display(Name = "Wedding Date")]
        public DateTime WeddingDate { get; set; }

        public DateTime CreatedAt { get; set; } = DateTime.Now;
        public DateTime UpdatedAt { get; set; } = DateTime.Now;

        public List<UserWeddingRSVP> RSVP { get; set; }

        public int UserId { get; set; }
        public User User { get; set; }

        public string WeddingName()
        {
            return Wedder1Name + " & " + Wedder2Name;
        }
    }
}

Controllers/WeddingController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using WeddingProj.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Http;
using Microsoft.EntityFrameworkCore;

namespace WeddingProj.Controllers
{
    public class WeddingController : Controller
    {
        private WeddingContext db;

        public WeddingController(WeddingContext context)
        {
            db = context;
        }
        private int? uid
        {
            get
            {
                return HttpContext.Session.GetInt32("UserID");
            }
        }

        private bool isLoggedIn
        {
            get
            {
                return uid != null;
            }
        }

        [HttpGet("/Wedding")]
        public IActionResult WeddingDisplay()
        {
            //pass in weddding list
            if (!isLoggedIn)
            {
                return RedirectToAction("Index", "Home");
            }

            List<Wedding> allWeddings = db.Weddings.ToList();

            foreach (var wedding in allWeddings)
            {
                if (wedding.WeddingDate <= DateTime.Now)
                {
                    db.Weddings.Remove(wedding);
                    db.SaveChanges();
                }
            }

            //Wedding.Models.Wedding is because my project and namespace is the same name (Don't do this in the future.)
            List<Wedding> newWeddings = db.Weddings
            .Include(c => c.RSVP)
            .ToList();
            return View("All", newWeddings);
        }

        [HttpGet("/NewWedding")]
        public IActionResult CreateWedding()
        {
            return View("NewWedding");
        }

        [HttpPost("/NewWedding")]
        public IActionResult NewWedding(Wedding newWedding)
        {
            if (!isLoggedIn)
            {
                return RedirectToAction("Index", "Home");
            }

            if (ModelState.IsValid == false)
            {
                return View("NewWedding");
            }
            if (newWedding.WeddingDate < DateTime.Now)
            {
                ModelState.AddModelError("Date", "Must be in the future!");
                return View("NewWedding");
            }
            User NewWedCreater = db.Users.FirstOrDefault(u => u.UserID == (int)uid);
            newWedding.User = NewWedCreater;
            db.Add(newWedding);
            db.SaveChanges();
            return RedirectToAction("WeddingDisplay");
        }

        [HttpPost("/Wedding/{weddingId}/Rsvp")]
        public IActionResult Rsvp(int weddingId)
        {
            if (!isLoggedIn)
            {
                return RedirectToAction("Index", "Home");
            }

            UserWeddingRSVP RSVP = db.RSVP
            .FirstOrDefault(r => r.UserId == (int)uid && r.WeddingId == weddingId);

            if (RSVP == null)
            {
                UserWeddingRSVP rsvp = new UserWeddingRSVP()
                {
                    WeddingId = weddingId,
                    UserId = (int)uid
                };
                db.RSVP.Add(rsvp);
            }
            else
            {
                db.RSVP.Remove(RSVP);
            }

            db.SaveChanges();
            return RedirectToAction("WeddingDisplay");
        }

        [HttpPost("Delete/{weddingId}/Delete")]
        public IActionResult Delete(int weddingId)
        {
            Wedding wedding = db.Weddings.FirstOrDefault(w => w.WeddingId == weddingId);

            if (wedding == null)
            {
                return RedirectToAction("WeddingDisplay");
            }

            db.Weddings.Remove(wedding);
            db.SaveChanges();
            return RedirectToAction("WeddingDisplay");
        }

        [HttpGet("/WeddingDetails/{weddingId}")]
        public IActionResult WeddingDetails(int weddingId)
        {
            if (!isLoggedIn)
            {
                return RedirectToAction("Index", "Home");
            }

            Wedding wedding = db.Weddings
            .Include(guest => guest.RSVP)
            // .Include(u => u.User)
            .ThenInclude(rsvp => rsvp.User)
            .FirstOrDefault(w => w.WeddingId == weddingId);
            Console.WriteLine(wedding);

            if (wedding == null)
            {
                return RedirectToAction("WeddingDisplay");
            }

            return View("WeddingDetails", wedding);

        }

        [HttpGet("/wedding/{weddingId}/edit")]
        public IActionResult Edit(int weddingId)
        {
            if (!isLoggedIn)
            {
                return RedirectToAction("Index", "Home");
            }
            Wedding wedding = db.Weddings.FirstOrDefault(w => w.WeddingId == weddingId);

            // The edit button will be hidden if you are not the author,
            // but the user could still type the URL in manually, so
            // prevent them from editing if they are not the author.
            if (wedding == null || wedding.UserId != uid)
            {
                return RedirectToAction("All");
            }

            return View("Edit", wedding);
        }

        [HttpPost("/weddings/{weddingId}/update")]
        public IActionResult Update(int weddingId, Wedding editedWedding)
        {
            if (ModelState.IsValid == false)
            {
                editedWedding.WeddingId = weddingId;
                // Send back to the page with the current form edited data to
                // display errors.
                return View("Edit", editedWedding);
            }

            Wedding dbWedding = db.Weddings.FirstOrDefault(w => w.WeddingId == weddingId);

            if (dbWedding == null)
            {
                return RedirectToAction("WeddingDisplay");
            }

            dbWedding.Wedder1Name = editedWedding.Wedder1Name;
            dbWedding.Wedder2Name = editedWedding.Wedder2Name;
            dbWedding.WeddingAddress = editedWedding.WeddingAddress;
            dbWedding.UpdatedAt = DateTime.Now;

            db.Weddings.Update(dbWedding);
            db.SaveChanges();

            /* 
            When redirecting to action that has params, you need to pass in a
            dict with keys that match param names and the value of the keys are
            the values for the params.
            */
            return RedirectToAction("Details", new { weddingId = weddingId });
        }

    }
}

Views/Wedding/All.cshtml
@model List<Wedding>
@{
    Wedding emptyWedding = new Wedding();
}


<body>
    <div style="display: flex; justify-content: space-between;">
        <h2>Welcome to the Wedding Planner</h2>
        <div>
            <a asp-controller="Wedding" asp-action="WeddingDisplay">Dashboard</a> | <form asp-controller="Home"
                asp-action="Logout" method="POST"><button class="btn btn-link">Logout</button></form>
        </div>
    </div>
    <div>
        <table class="table table-dark table-striped">
            <thead>
                <tr>
                    <th scope="col">Wedding</th>
                    <th scope="col">Date</th>
                    <th scope="col">Guests</th>
                    <th scope="col">Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach (Wedding wed in Model)
                {
                    bool alreadyRSVP = wed.RSVP.Any(r => Context.Session.GetInt32("UserID") == r.UserId);
                    <tr>
                        <td><a asp-controller="Wedding" asp-action="WeddingDetails"
                            asp-route-weddingId="@wed.WeddingId">@wed.WeddingName()</a></td>
                        <td>@wed.WeddingDate.ToString("MMMM dd, yyyy")</td>
                        @* #of people that have RSVP'd *@
                        <td>@wed.RSVP.Count</td>
                        <td>
                            @if (wed.UserId == Context.Session.GetInt32("UserID"))
                            {
                                <form asp-controller="Wedding" asp-action="Delete" asp-route-weddingId="@wed.WeddingId"
                            method="POST">
                                    <button class="btn btn-outline-danger btn-link">Delete</button>
                                </form>
                            }
                            else
                            {
                                <form asp-controller="Wedding" asp-action="Rsvp" asp-route-weddingId="@wed.WeddingId">
                                    @if (alreadyRSVP)
                                    {
                                        <button class="btn btn-link">Un-RSVP</button>
                                    }
                                    else
                                    {
                                        <button class="btn btn-link">RSVP</button>
                                    }
                                </form>
                            }
                        </td>
                    </tr>
                }
            </tbody>
        </table>
        <a href="/NewWedding">New Wedding</a>
    </div>
    </div>
    </div>

</body>

</html>

Views/Wedding/NewWedding.cshtml
@model Wedding

<div style="display: flex; justify-content: space-between;">
    <h2>Plan Your Wedding!</h2>
    <div>
        <a asp-controller="Wedding" asp-action="WeddingDisplay">Dashboard</a> | <form asp-controller="Home"
            asp-action="Logout" method="POST"><button class="btn btn-link">Logout</button></form>
    </div>
</div>
<form asp-controller="Wedding" asp-action="NewWedding" method="POST">
    <div>
        <label asp-for="Wedder1Name">Wedder One: </label>
        <span asp-validation-for="Wedder1Name"></span>
        <input asp-for="Wedder1Name" />
    </div>
    <div>
        <label asp-for="Wedder2Name">Wedder Two: </label>
        <span asp-validation-for="Wedder2Name"></span>
        <input asp-for="Wedder2Name" />
    </div>
    <div>
        <label asp-for="WeddingDate">Wedding Date: </label>
        <span asp-validation-for="WeddingDate"></span>
        <input asp-for="WeddingDate" />
    </div>
    <div>
        <label asp-for="WeddingAddress">Wedding Address: </label>
        <span asp-validation-for="WeddingAddress"></span>
        <input asp-for="WeddingAddress" />
    </div>
    </div>
    <button>Create</button>
</form>

Views/Wedding/WeddingDetails.cshtml
@model Wedding

<div style="display: flex; justify-content: space-between;">
    <h2>@Model.Wedder1Name and @Model.Wedder2Name's Wedding!</h2>
    <div>
        <a asp-controller="Wedding" asp-action="WeddingDisplay">Dashboard</a> | <form asp-controller="Home"
            asp-action="Logout" method="POST"><button class="btn btn-link">Logout</button></form>
    </div>
</div>
<div>Date: @Model.WeddingDate.ToString("MMMM dd, yyyy")</div>

<div>
    <div>Guests:</div>
    @foreach (var guest in Model.RSVP)
    {
        <p>@guest.User.FirstName @guest.User.LastName</p>
    }
</div>